version: "3.9"
services:
  redisdb:
    image: redis
    volumes:
      - .\redis_data:/data
  greetingsvc:
    image: nagabhushanamn/greeting-service
    ports:
      - "8181:8181"
  greetingui:
    image: nagabhushanamn/greeting-ui
    ports:
      - "80:80"
