pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                 git branch: 'main', url: 'https://github.com/nagcloudlab/greeting-repo'
            }
        }
        stage('Compile') {
            steps {
             dir('greeting-service'){
                sh 'pwd'
                sh './mvnw clean compile'
             }
            }
        }
        stage('Unit-Testing') {
            steps {
              dir('greeting-service'){
                 sh './mvnw test'
              }
            }
        }
        stage('Integration') {
            steps {
                echo 'Integration Testing'
            }
        }
        stage('Package') {
             steps {
              dir('greeting-service'){
                 sh './mvnw package'
              }
            }
        }
        stage('DockerBuild') {
             steps {
              dir('greeting-service'){
                 sh 'docker build -t nagabhushanamn/greeting-service .'
              }
            }
        }
//         stage('DockerPush') {
//              steps {
//               dir('greeting-service'){
//                  bat 'docker push nagabhushanamn/greeting-service'
//               }
//             }
//         }
    }
}