pipeline {
    agent any
    environment {
    	DOCKERHUB_CREDENTIALS=credentials('docker-hub-credentials')
    }
    stages {
        stage('Checkout') {
            steps {
                 git branch: 'main', url: 'https://github.com/nagcloudlab/greeting-repo'
            }
        }
        stage('Compile') {
            steps {
             dir('greeting-service'){
                sh 'chmod +x mvnw'
                sh './mvnw clean compile'
             }
            }
        }
        stage('Unit-Testing') {
            steps {
              dir('greeting-service'){
                 sh './mvnw test'
              }
            }
        }
        stage('Integration') {
            steps {
                echo 'Integration Testing'
            }
        }
        stage('Package') {
             steps {
              dir('greeting-service'){
                 sh './mvnw package'
              }
            }
        }
        stage('DockerBuild') {
             steps {
              dir('greeting-service'){
                 sh 'docker build -t nagabhushanamn/greeting-service .'
              }
            }
        }
        stage('Dockerhub Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

        stage('DockerPush') {
             steps {
              dir('greeting-service'){
                 sh 'docker push nagabhushanamn/greeting-service'
              }
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}