pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                bat '.\mvnw clean compile'
            }
        }
        stage('Unit-Testing') {
            steps {
                bat '.\mvnw test'
            }
        }
        stage('Integration') {
            steps {
                echo 'Integration Testing'
            }
        }
        stage('Package') {
            steps {
                echo '.\mvnw package'
            }
        }
    }
}